{{ range .Values.apps -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-loadbalancer
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ .name }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .name }}
{{ end -}}
