apps:
  orders:
    name: orders
    image: orders-service
    port: 8080
  products:
    name: products
    image: products-service
    port: 8081
  users:
    name: users
    image: users-service
    port: 8082

port: 8080

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 2
  periodSeconds: 10  
readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5 

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

env:
  - name: API_KEY
    valueFrom:
      secretKeyRef:
        name: services-api-key
        key: API_KEY

secrets:
  apiKey: ZGQzZjQ0YmItMzIyNy00YzgwLTlmMWEtYmQ4MDI3NDI5NTU3
